// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Direct Supabase configuration for new database
const SUPABASE_URL = "https://rqheobctitidlymdbuxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_Q9V8oVdfd8ILU9XnO79kqQ_ILtDKoqp";

// Debug logging to verify direct configuration
console.log('🔍 Direct Supabase URL:', SUPABASE_URL);
console.log('🔍 Direct Supabase Key:', SUPABASE_PUBLISHABLE_KEY ? 'Key loaded' : 'Key missing');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Clear any cached Supabase data to force new connection
if (typeof window !== 'undefined') {
  localStorage.removeItem('supabase.auth.token');
  localStorage.removeItem('supabase.auth.refreshToken');
  sessionStorage.removeItem('supabase.auth.token');
  sessionStorage.removeItem('supabase.auth.refreshToken');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});